name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SonarQube Scanner
      run: |
        curl -o sonarqube.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonarqube.zip
        mv sonar-scanner-5.0.1.3006-linux sonar-scanner

    - name: Run SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=Github-repos-scan \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://44.207.4.204:9000 \
          -Dsonar.login=$SONAR_TOKEN
